In [1]:
import pandas as pd
#работа с данными

In [2]:
from pandas import Series, DataFrame

In [3]:
obj = pd.Series([4,7,-5,3])
print(obj)

0    4
1    7
2   -5
3    3
dtype: int64


In [4]:
print(obj.values)
print(obj.index)

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [5]:
obj.index = ["Bob","Steve","Jeff","Ryan"]
print(obj)

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64


In [6]:
obj2 = pd.Series([7,4,-5])
obj2.index = ['seven','four','minus five']
print(obj2["seven"])
print(obj2[['seven','four','minus five']])

7
seven         7
four          4
minus five   -5
dtype: int64


In [7]:
import numpy as np
print(obj2[obj2 > 0], "\n")
print(obj2 * 2, "\n")
print(np.exp(obj2))

seven    7
four     4
dtype: int64 

seven         14
four           8
minus five   -10
dtype: int64 

seven         1096.633158
four            54.598150
minus five       0.006738
dtype: float64


In [8]:
sdata = {"MSC":35000,"KALM":1220,"VORON":3500,"ALTAI":1500}
obj3 = pd.Series(sdata)
print(obj3)

MSC      35000
KALM      1220
VORON     3500
ALTAI     1500
dtype: int64


In [9]:
print(pd.isnull(obj3),"\n")
print(pd.notnull(obj3),"\n")

MSC      False
KALM     False
VORON    False
ALTAI    False
dtype: bool 

MSC      True
KALM     True
VORON    True
ALTAI    True
dtype: bool 



In [10]:
obj3. name = 'population'
obj3.index.name = 'state'
print(obj3)

state
MSC      35000
KALM      1220
VORON     3500
ALTAI     1500
Name: population, dtype: int64


In [11]:
data = {'state':["MSC","KALM","VORON","ALTAI"],
        'year': [35000,1220,3500,1500],
        "pop": [1.5,1.6,3.5,4.3]}
frame = pd.DataFrame(data)
print(frame)

   state   year  pop
0    MSC  35000  1.5
1   KALM   1220  1.6
2  VORON   3500  3.5
3  ALTAI   1500  4.3


In [12]:
frame = pd.DataFrame(data,columns = ['year','pop','state'])
print(frame)

    year  pop  state
0  35000  1.5    MSC
1   1220  1.6   KALM
2   3500  3.5  VORON
3   1500  4.3  ALTAI


In [13]:
frame2 = pd.DataFrame(data,columns = ['year','pop','state','debt'],
                     index=["one","two","three","four",])
print(frame2,"\n")
print(frame2.columns)

        year  pop  state debt
one    35000  1.5    MSC  NaN
two     1220  1.6   KALM  NaN
three   3500  3.5  VORON  NaN
four    1500  4.3  ALTAI  NaN 

Index(['year', 'pop', 'state', 'debt'], dtype='object')


In [14]:
print(frame2.loc['three'])

year      3500
pop        3.5
state    VORON
debt       NaN
Name: three, dtype: object


In [15]:
frame2['debt'] = 16.5
print(frame2,"\n")
frame2['debt'] = [i for i in range(1,5)]
print(frame2)

        year  pop  state  debt
one    35000  1.5    MSC  16.5
two     1220  1.6   KALM  16.5
three   3500  3.5  VORON  16.5
four    1500  4.3  ALTAI  16.5 

        year  pop  state  debt
one    35000  1.5    MSC     1
two     1220  1.6   KALM     2
three   3500  3.5  VORON     3
four    1500  4.3  ALTAI     4


In [16]:
val = pd.Series([-1.2,-1.5,-1.8],index = ['two','four','three'])
frame2['debt']=val
print(frame2)

        year  pop  state  debt
one    35000  1.5    MSC   NaN
two     1220  1.6   KALM  -1.2
three   3500  3.5  VORON  -1.8
four    1500  4.3  ALTAI  -1.5


In [17]:
frame2['eastern'] = frame2.state == "ALTAI"
frame2

year  pop  state  debt  eastern
one    35000  1.5    MSC   NaN    False
two     1220  1.6   KALM  -1.2    False
three   3500  3.5  VORON  -1.8    False
four    1500  4.3  ALTAI  -1.5     True

In [18]:
del frame2['eastern']
print(frame2.columns,'\n')
print(frame2)

Index(['year', 'pop', 'state', 'debt'], dtype='object') 

        year  pop  state  debt
one    35000  1.5    MSC   NaN
two     1220  1.6   KALM  -1.2
three   3500  3.5  VORON  -1.8
four    1500  4.3  ALTAI  -1.5


In [19]:
pop = {"Nevada":[2.4,2.9,4.2],
      'Ohio':[1.8,4.2,1.4]}

frame3 = pd.DataFrame(pop,index = [2001,2002,2003])
frame3

Nevada  Ohio
2001     2.4   1.8
2002     2.9   4.2
2003     4.2   1.4

In [20]:
pdata = {"Ohio":frame3["Ohio"][:-1],
      'Nevada':frame3["Nevada"][:2]}
pd.DataFrame(pdata)

C:\Users\Balah\AppData\Local\Temp\ipykernel_3240\4097961336.py:1: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  pdata = {"Ohio":frame3["Ohio"][:-1],
C:\Users\Balah\AppData\Local\Temp\ipykernel_3240\4097961336.py:2: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  'Nevada':frame3["Nevada"][:2]}


Ohio  Nevada
2001   1.8     2.4
2002   4.2     2.9

In [21]:
frame3.index.name = "year";frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.8
2002      2.9   4.2
2003      4.2   1.4

In [22]:
frame3.values

array([[2.4, 1.8],
       [2.9, 4.2],
       [4.2, 1.4]])

In [23]:
obj = pd.Series(range(3),index=['a',"b","c"])
index = obj.index
print(index)
print(index[1:])

Index(['a', 'b', 'c'], dtype='object')
Index(['b', 'c'], dtype='object')


In [24]:
labels = pd.Index(np.arange(6,9))
print(labels)
obj4 = pd.Series([1.4,-3.2,0],index=labels)
print(obj4)
print(obj4.index==labels)
print(obj4.index is labels)

Int64Index([6, 7, 8], dtype='int64')
6    1.4
7   -3.2
8    0.0
dtype: float64
[ True  True  True]
True


In [25]:
obj = pd.Series([4.5,43.32,123.41,12.12],index=['b','d','c','a'])
obj

b      4.50
d     43.32
c    123.41
a     12.12
dtype: float64

In [26]:
obj2= obj.reindex(['a','b','c','d','e'])
obj2

a     12.12
b      4.50
c    123.41
d     43.32
e       NaN
dtype: float64

In [27]:
obj3 = pd.Series(["blue","red","green"],index=[0,2,4])
print(obj3,'\n')
obj3 = obj3.reindex(range(8),method="ffill")
print(obj3)

0     blue
2      red
4    green
dtype: object 

0     blue
1     blue
2      red
3      red
4    green
5    green
6    green
7    green
dtype: object


In [28]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)),
                    index=['a','c','d','e'],
                    columns=["MSC","KALM","VORON"])
print(frame,'\n')
frame2 = frame.reindex({'a','b','c','d'})
print(frame2)
frame2 = frame.reindex(['a','b','c','d'])
print(frame2)

   MSC  KALM  VORON
a    0     1      2
c    3     4      5
d    6     7      8
e    9    10     11 

   MSC  KALM  VORON
b  NaN   NaN    NaN
c  3.0   4.0    5.0
d  6.0   7.0    8.0
a  0.0   1.0    2.0
   MSC  KALM  VORON
a  0.0   1.0    2.0
b  NaN   NaN    NaN
c  3.0   4.0    5.0
d  6.0   7.0    8.0


In [29]:
resp = ["MSC","KALM","VORON","ALTAI"]
frame.reindex(columns=resp)

MSC  KALM  VORON  ALTAI
a    0     1      2    NaN
c    3     4      5    NaN
d    6     7      8    NaN
e    9    10     11    NaN

In [30]:
obj = pd.Series(np.arange(5.),index = ['a','b','c','d','e'])
print(obj,'\n')
new_obj = obj.drop('c')
print(new_obj,'\n')
print(obj.drop(["d","c"]),'\n')

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64 

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64 

a    0.0
b    1.0
e    4.0
dtype: float64 



In [31]:
print(obj['b':"d"])
obj["b":"d"]=3
print(obj)

b    1.0
c    2.0
d    3.0
dtype: float64
a    0.0
b    3.0
c    3.0
d    3.0
e    4.0
dtype: float64


In [45]:
print(frame)
print(frame[:2],'\n')
print(frame[frame["VORON"]<2],'\n')
print(frame<2,'\n')
frame[frame>2]=0
print(frame)

   MSC  KALM  VORON
a    0     1      2
c    0     0      0
d    0     0      0
e    0     0      0
   MSC  KALM  VORON
a    0     1      2
c    0     0      0 

   MSC  KALM  VORON
c    0     0      0
d    0     0      0
e    0     0      0 

    MSC  KALM  VORON
a  True  True  False
c  True  True   True
d  True  True   True
e  True  True   True 

   MSC  KALM  VORON
a    0     1      2
c    0     0      0
d    0     0      0
e    0     0      0


In [36]:
print(frame["MSC"])
print(frame[["MSC","KALM"]])

a    0
c    3
d    6
e    9
Name: MSC, dtype: int32
   MSC  KALM
a    0     1
c    3     4
d    6     7
e    9    10


In [48]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=["a","c","d","e"])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.3],index=["a","c","e","f","g"])
print(s1)
print(s2)
print(s1+s2)


a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64
a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.3
dtype: float64
a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64


In [51]:
arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [53]:
obj = pd.Series(range(4),index=["b","d",'c',"a"])
obj.sort_index()

a    3
b    0
c    2
d    1
dtype: int64

In [62]:
frame = pd.DataFrame(np.arange(12).reshape((3,4)),
                    columns=['a','c','d','b'],
                    index=["three","two","one"])
print(frame.sort_index())
print(frame.sort_index(axis=1),'\n')
print(frame.sort_index(axis=1,ascending=False))

       a  c   d   b
one    8  9  10  11
three  0  1   2   3
two    4  5   6   7
       a   b  c   d
three  0   3  1   2
two    4   7  5   6
one    8  11  9  10 

        d  c   b  a
three   2  1   3  0
two     6  5   7  4
one    10  9  11  8


In [66]:
obj = pd.Series([4,5,np.NaN,2,-1])
obj.sort_values()

4   -1.0
3    2.0
0    4.0
1    5.0
2    NaN
dtype: float64

In [67]:
frame = pd.DataFrame({'b':[4,2,-2,4],'a':[1,4,12,4]})
frame

b   a
0  4   1
1  2   4
2 -2  12
3  4   4

In [68]:
frame.sort_values(by='b')

b   a
2 -2  12
1  2   4
0  4   1
3  4   4

In [69]:
obj.rank()

0    3.0
1    4.0
2    NaN
3    2.0
4    1.0
dtype: float64

In [70]:
frame.rank(axis='columns')

b    a
0  2.0  1.0
1  1.0  2.0
2  1.0  2.0
3  1.5  1.5

In [71]:
frame.rank(axis='rows')

b    a
0  3.5  1.0
1  2.0  2.5
2  1.0  4.0
3  3.5  2.5

In [76]:
obj = pd.Series(range(5),index=['b','b','a',"a",'c'])
obj

b    0
b    1
a    2
a    3
c    4
dtype: int64

In [78]:
obj.index.is_unique

False

In [79]:
obj['a']

a    2
a    3
dtype: int64

In [80]:
frame = pd.DataFrame(np.random.randn(4,3),index=['a','a','b','b'])
frame

0         1         2
a  0.389596 -0.219119 -1.027851
a  0.454455 -1.084845  0.048210
b -0.382219 -1.873332 -0.969788
b -0.382666  1.527885 -1.405146

In [81]:
frame.loc['b']

0         1         2
b -0.382219 -1.873332 -0.969788
b -0.382666  1.527885 -1.405146

In [83]:
frame.sum(axis='columns')

a   -0.857374
a   -0.582180
b   -3.225339
b   -0.259927
dtype: float64

In [84]:
frame.mean(axis='columns',skipna=False)

a   -0.285791
a   -0.194060
b   -1.075113
b   -0.086642
dtype: float64

In [85]:
frame.idxmax()

0    a
1    b
2    a
dtype: object

In [86]:
frame.idxmin()

0    b
1    b
2    b
dtype: object

In [87]:
frame.describe()

0         1         2
count  4.000000  4.000000  4.000000
mean   0.019792 -0.412353 -0.838644
std    0.465214  1.459288  0.621941
min   -0.382666 -1.873332 -1.405146
25%   -0.382331 -1.281967 -1.122175
50%    0.003688 -0.651982 -0.998820
75%    0.405811  0.217632 -0.715289
max    0.454455  1.527885  0.048210

In [96]:
obj.unique

<bound method Series.unique of b    0
b    1
a    2
a    3
c    4
dtype: int64>

In [97]:
obj.value_counts()

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [98]:
obj.isin

<bound method Series.isin of b    0
b    1
a    2
a    3
c    4
dtype: int64>